"""Integration tests for specforge validate-prompts command — T033 through T035."""

from __future__ import annotations

import json
from pathlib import Path

from click.testing import CliRunner

from specforge.cli.main import cli
from specforge.core.config import GOVERNANCE_DOMAINS


def _write_config(project_dir: Path, stack: str = "agnostic") -> None:
    config_dir = project_dir / ".specforge"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "config.json").write_text(
        json.dumps({
            "project_name": "test-project",
            "stack": stack,
            "version": "1.0",
            "created_at": "2026-03-15",
        }),
        encoding="utf-8",
    )


def _write_governance_file(
    project_dir: Path,
    domain: str,
    stack: str,
    thresholds_line: str = "threshold: max_lines=100",
    rule_id: str | None = None,
) -> None:
    prompts_dir = project_dir / ".specforge" / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)

    # Agnostic domains
    agnostic_domains = {"architecture", "security"}
    if domain in agnostic_domains or stack == "agnostic":
        fname = f"{domain}.prompts.md"
    else:
        fname = f"{domain}.{stack}.prompts.md"

    if rule_id is None:
        rule_id = f"{domain[:4].upper()}-001"

    precedence_map = {
        "security": 1, "architecture": 2, "backend": 3,
        "frontend": 3, "database": 3, "testing": 4, "cicd": 5,
    }
    precedence = precedence_map.get(domain, 3)

    content = f"""\
<!-- Generated by SpecForge - do not edit manually above the Rules section -->

# {domain.title()} Governance Prompt

## Meta
domain: {domain}
stack: {stack}
version: 1.0
precedence: {precedence}
checksum: abc123

## Precedence
Position {precedence} in the hierarchy.

## Rules

### {rule_id}: Test Rule
severity: ERROR
scope: all files
rule: All code MUST follow governance rules for {domain}.
{thresholds_line}
example_correct: |
  # correct
example_incorrect: |
  # incorrect
"""
    (prompts_dir / fname).write_text(content, encoding="utf-8")


def _write_all_governance_files(
    project_dir: Path,
    stack: str = "agnostic",
    overrides: dict[str, str] | None = None,
) -> None:
    """Write all 7 governance files, with optional threshold overrides."""
    overrides = overrides or {}
    for domain in GOVERNANCE_DOMAINS:
        thresh = overrides.get(domain, f"threshold: max_lines=100")
        _write_governance_file(project_dir, domain, stack, thresholds_line=thresh)


class TestValidatePromptsNoConflicts:
    """T033 — validate-prompts exits 0 when no conflicts."""

    def test_exit_0_with_no_conflicts(self, tmp_path: Path) -> None:
        _write_config(tmp_path, "agnostic")
        _write_all_governance_files(tmp_path, "agnostic")

        runner = CliRunner()
        with runner.isolated_filesystem(temp_dir=tmp_path):
            result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert result.exit_code == 0, result.output

    def test_no_conflicts_message_in_output(self, tmp_path: Path) -> None:
        _write_config(tmp_path, "agnostic")
        _write_all_governance_files(tmp_path, "agnostic")

        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert result.exit_code == 0
        assert "No conflicts" in result.output or "no conflicts" in result.output.lower()


class TestValidatePromptsWithConflicts:
    """T034 — validate-prompts exits 1 and reports conflicts."""

    def test_exit_1_with_conflicts(self, tmp_path: Path) -> None:
        _write_config(tmp_path, "agnostic")
        # architecture (precedence 2) and backend (precedence 3) conflict on max_class_lines
        _write_all_governance_files(
            tmp_path,
            "agnostic",
            overrides={
                "architecture": "threshold: max_class_lines=50",
                "backend": "threshold: max_class_lines=200",
            },
        )

        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert result.exit_code == 1, result.output

    def test_conflict_includes_threshold_key_in_output(self, tmp_path: Path) -> None:
        _write_config(tmp_path, "agnostic")
        _write_all_governance_files(
            tmp_path,
            "agnostic",
            overrides={
                "architecture": "threshold: max_class_lines=50",
                "backend": "threshold: max_class_lines=200",
            },
        )

        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert "max_class_lines" in result.output

    def test_conflict_includes_domain_names_in_output(self, tmp_path: Path) -> None:
        _write_config(tmp_path, "agnostic")
        _write_all_governance_files(
            tmp_path,
            "agnostic",
            overrides={
                "architecture": "threshold: max_class_lines=50",
                "backend": "threshold: max_class_lines=200",
            },
        )

        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert "architecture" in result.output
        assert "backend" in result.output

    def test_two_conflicts_both_reported(self, tmp_path: Path) -> None:
        _write_config(tmp_path, "agnostic")
        _write_all_governance_files(
            tmp_path,
            "agnostic",
            overrides={
                "architecture": "threshold: max_class_lines=50, max_method_lines=20",
                "backend": "threshold: max_class_lines=200, max_method_lines=40",
            },
        )

        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert result.exit_code == 1
        assert "max_class_lines" in result.output
        assert "max_method_lines" in result.output

    def test_conflict_includes_winning_value(self, tmp_path: Path) -> None:
        _write_config(tmp_path, "agnostic")
        _write_all_governance_files(
            tmp_path,
            "agnostic",
            overrides={
                "architecture": "threshold: max_class_lines=50",  # wins (prec 2)
                "backend": "threshold: max_class_lines=200",
            },
        )

        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        # Winning value is 50 (architecture has higher precedence)
        assert "50" in result.output
        assert "architecture" in result.output


class TestValidatePromptsNotInitialized:
    """T035 — validate-prompts exits 2 when not initialized."""

    def test_exit_2_when_no_specforge_dir(self, tmp_path: Path) -> None:
        # Empty directory — no .specforge/
        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert result.exit_code == 2, result.output

    def test_error_message_suggests_init(self, tmp_path: Path) -> None:
        runner = CliRunner()
        result = runner.invoke(cli, ["validate-prompts", "--project", str(tmp_path)])

        assert "init" in result.output.lower() or "specforge init" in result.output
