"""Constants, type literals, and configuration for SpecForge core."""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from specforge.core.template_models import TemplateVarSchema

AgentName = Literal[
    "claude", "copilot", "gemini", "cursor", "windsurf", "codex", "agnostic"
]

StackName = Literal["dotnet", "nodejs", "python", "go", "java", "agnostic"]

AGENT_PRIORITY: list[str] = [
    "claude",
    "copilot",
    "gemini",
    "cursor",
    "windsurf",
    "codex",
]

SUPPORTED_STACKS: list[str] = [
    "dotnet",
    "nodejs",
    "python",
    "go",
    "java",
]

AGENT_EXECUTABLES: dict[str, list[str]] = {
    "claude": ["claude"],
    "copilot": ["copilot"],
    "gemini": ["gemini"],
    "cursor": ["cursor"],
    "windsurf": ["windsurf"],
    "codex": ["codex"],
}

PREREQUISITES: list[str] = ["git", "python", "uv"]

# Scaffold directory structure (relative to .specforge/)
SCAFFOLD_DIRS: list[str] = [
    ".specforge",
    ".specforge/memory",
    ".specforge/features",
    ".specforge/prompts",
    ".specforge/scripts",
    ".specforge/templates/features",
]

# Valid project name pattern
PROJECT_NAME_PATTERN = r"^[a-zA-Z0-9_-]+$"

# Default git commit message for scaffold
INIT_COMMIT_MESSAGE = "chore: init specforge scaffold"

# Stack hints for template rendering
STACK_HINTS: dict[str, str] = {
    "dotnet": "C#/.NET",
    "nodejs": "Node.js/TypeScript",
    "python": "Python",
    "go": "Go",
    "java": "Java",
    "agnostic": "Language-agnostic",
}

# Install hints for prerequisites
INSTALL_HINTS: dict[str, str] = {
    "git": "https://git-scm.com/downloads",
    "python": "https://python.org/downloads",
    "uv": "https://docs.astral.sh/uv/getting-started/installation/",
    "claude": "https://claude.ai/download",
    "copilot": "https://github.com/features/copilot",
    "gemini": "https://ai.google.dev/gemini-api/docs/downloads",
    "cursor": "https://cursor.com",
    "windsurf": "https://windsurf.com",
    "codex": "https://github.com/openai/codex",
}

# ── Template Engine Constants (Feature 002) ──────────────────────────

PROMPT_AGENT_NAMES: list[str] = [
    "backend",
    "frontend",
    "database",
    "security",
    "testing",
    "cicd",
    "api-design",
]

FEATURE_TEMPLATE_NAMES: list[str] = [
    "spec",
    "research",
    "datamodel",
    "plan",
    "checklist",
    "edge-cases",
    "tasks",
]

GENERATION_HEADER = "<!-- Generated by SpecForge — do not edit manually -->"


# ── Governance Layer Constants (Feature 003) ──────────────────────────

GOVERNANCE_DOMAINS: list[str] = [
    "architecture",
    "backend",
    "frontend",
    "database",
    "security",
    "testing",
    "cicd",
]

PRECEDENCE_ORDER: list[str] = [
    "security",
    "architecture",
    "backend",
    "frontend",
    "database",
    "testing",
    "cicd",
]

EQUAL_PRIORITY_DOMAINS: frozenset[str] = frozenset({"backend", "frontend", "database"})

AGNOSTIC_GOVERNANCE_DOMAINS: frozenset[str] = frozenset({"architecture", "security"})

GOVERNANCE_FILE_PATTERN: str = "{domain}.{stack}.prompts.md"
GOVERNANCE_AGNOSTIC_FILE_PATTERN: str = "{domain}.prompts.md"

SPECFORGE_CONFIG_FILE: str = ".specforge/config.json"


# ── Architecture Decomposer Constants (Feature 004) ──────────────────

ArchitectureType = Literal["monolithic", "microservice", "modular-monolith"]

VALID_ARCHITECTURES: list[str] = ["monolithic", "microservice", "modular-monolith"]

OVER_ENGINEERING_THRESHOLD: int = 5

MANIFEST_PATH: str = ".specforge/manifest.json"

STATE_PATH: str = ".specforge/decompose-state.json"

COMMUNICATION_MAP_PATH: str = ".specforge/communication-map.md"

FEATURES_DIR: str = ".specforge/features"

FEATURE_CATEGORIES: list[str] = [
    "foundation",
    "core",
    "supporting",
    "integration",
    "admin",
]

FEATURE_PRIORITIES: list[str] = ["P0", "P1", "P2", "P3"]

COMMUNICATION_PATTERNS: list[str] = ["sync-rest", "sync-grpc", "async-event"]

DECOMPOSITION_STEPS: list[str] = [
    "architecture",
    "decomposition",
    "mapping",
    "review",
    "complete",
]

SCALING_PROFILE: dict[str, str] = {
    "foundation": "low",
    "core": "medium",
    "supporting": "medium",
    "integration": "high-variance",
    "admin": "low",
}

FAILURE_MODE: dict[str, str] = {
    "foundation": "infrastructure",
    "core": "business-logic",
    "supporting": "business-logic",
    "integration": "external-dependency",
    "admin": "operational",
}

MAX_FEATURES_PER_SERVICE: int = 4

AFFINITY_SAME_CATEGORY: int = 3
AFFINITY_SHARED_DATA: int = 2
AFFINITY_DIFF_SCALING: int = -2
AFFINITY_DIFF_FAILURE: int = -2
AFFINITY_MERGE_THRESHOLD: int = 3

SCHEMA_VERSION: str = "1.0"

CLARIFICATION_QUESTIONS: list[str] = [
    "What domain or industry is this application for?",
    "Who are the primary users?",
    "What is the core action users perform?",
    "What scale do you expect (personal, team, enterprise)?",
    "Are there any external integrations (payments, APIs, social login)?",
]

MIN_KEYWORD_SCORE: int = 2


# ── Spec Generation Pipeline Constants (Feature 005) ─────────────────

PIPELINE_STATE_FILENAME: str = ".pipeline-state.json"
PIPELINE_LOCK_FILENAME: str = ".pipeline-lock"
LOCK_STALE_THRESHOLD_MINUTES: int = 30

PIPELINE_PHASE_STATUSES: list[str] = [
    "pending",
    "in-progress",
    "complete",
    "failed",
]

PIPELINE_PHASES: list[str] = [
    "spec",
    "research",
    "datamodel",
    "edgecase",
    "plan",
    "checklist",
    "tasks",
]

SHARED_ENTITIES_PATH: str = ".specforge/shared_entities.md"
CONTRACTS_DIR: str = "contracts"
STUB_CONTRACT_SUFFIX: str = ".stub.json"
INTERFACES_FILENAME: str = "interfaces.md"


# ── Research & Clarification Engine Constants (Feature 006) ───────────


AMBIGUITY_CATEGORIES: tuple[str, ...] = (
    "domain",
    "technical",
    "service_boundary",
    "communication",
)

FINDING_STATUSES: tuple[str, ...] = (
    "RESOLVED",
    "UNVERIFIED",
    "BLOCKED",
    "CONFLICTING",
)

VAGUE_TERM_PATTERNS: tuple[str, ...] = (
    r"\bappropriate(ly)?\b",
    r"\bas needed\b",
    r"\bsuitable|suitably\b",
    r"\bproper(ly)?\b",
    r"\brelevant\b",
    r"\betc\.\b",
    r"\bvarious\b",
    r"\brobust(ly|ness)?\b",
    r"\bintuitive(ly)?\b",
    r"\bflexible|flexibility\b",
)

CLARIFICATION_SECTION_HEADING: str = "## Clarifications"
SESSION_HEADING_PREFIX: str = "### Session"
CLARIFICATION_REPORT_FILENAME: str = "clarifications-report.md"

IMPACT_PRIORITY: dict[str, int] = {
    "service_boundary": 1,
    "domain": 2,
    "technical": 3,
    "communication": 4,
}

BOUNDARY_STOP_WORDS: frozenset[str] = frozenset({
    "the", "a", "an", "and", "or", "is", "are", "was", "were",
    "in", "on", "at", "to", "for", "of", "with", "by", "from",
    "as", "it", "its", "this", "that", "be", "has", "have", "had",
    "not", "will", "can", "should", "must", "each", "all", "any",
    "service", "system", "feature", "support", "manage", "management",
    "provide", "handle", "allow", "enable", "include", "use",
    "based", "using", "via", "also", "may", "which", "when",
})

ANSWER_TEMPLATES: dict[str, tuple[str, ...]] = {
    "domain": (
        "Define specific business rules for {concept}",
        "Use industry-standard definition of {concept}",
        "Defer to domain expert for {concept} requirements",
        "Split {concept} into sub-categories with separate rules",
    ),
    "technical": (
        "Use {concept} with default configuration",
        "Evaluate alternatives to {concept} before committing",
        "Use {concept} for MVP, revisit for production",
    ),
    "service_boundary": (
        "{concept} owned by {service_a}",
        "{concept} owned by {service_b}",
        "Extract {concept} into shared library",
        "Duplicate {concept} with eventual consistency",
    ),
    "communication": (
        "Synchronous (REST/gRPC) for {concept}",
        "Asynchronous (events/messages) for {concept}",
        "Hybrid: sync for queries, async for commands",
    ),
}

UBIQUITY_THRESHOLD: float = 0.6

REMAP_QUESTION_TOPICS: tuple[str, ...] = (
    "service boundaries",
    "communication patterns",
    "data ownership",
    "shared state",
    "eventual consistency",
)

MICROSERVICE_RESEARCH_TOPICS: tuple[dict[str, str], ...] = (
    {
        "topic": "Docker base image selection",
        "description": "Evaluate base images for containerized deployment "
        "(alpine, distroless, slim variants)",
    },
    {
        "topic": "Health check endpoint design",
        "description": "Liveness and readiness probes for "
        "container orchestration",
    },
    {
        "topic": "Message broker comparison",
        "description": "Compare message brokers for async communication "
        "(RabbitMQ, Kafka, Redis Streams)",
    },
)


def get_constitution_vars() -> TemplateVarSchema:
    """Variable schema for constitution templates."""
    from specforge.core.template_models import TemplateVarSchema

    return TemplateVarSchema(
        required={
            "project_name": str,
            "agent": str,
            "stack": str,
            "date": str,
            "stack_hint": str,
        },
    )


def get_prompt_vars() -> TemplateVarSchema:
    """Variable schema for prompt templates."""
    from specforge.core.template_models import TemplateVarSchema

    return TemplateVarSchema(
        required={
            "project_name": str,
            "agent": str,
            "stack": str,
            "date": str,
            "stack_hint": str,
        },
        optional={
            "conventions": (str, ""),
            "patterns": (str, ""),
        },
    )


def get_feature_vars() -> TemplateVarSchema:
    """Variable schema for feature templates."""
    from specforge.core.template_models import TemplateVarSchema

    return TemplateVarSchema(
        required={
            "project_name": str,
            "date": str,
        },
        optional={
            "feature_name": (str, ""),
            "stack": (str, "agnostic"),
            "stack_hint": (str, "Language-agnostic"),
            # Pipeline context (Feature 005)
            "service": (dict, {}),
            "architecture": (str, ""),
            "features": (list, []),
            "dependencies": (list, []),
            "capabilities": (list, []),
            "entities": (list, []),
            "adapter_sections": (list, []),
            "adapter_tasks": (list, []),
            "adapter_edge_cases": (list, []),
            "adapter_checklist": (list, []),
            "adapter_research_extras": (list, []),
            "datamodel_context": (dict, {}),
            "prompt_context": (str, ""),
            "events": (list, []),
            "communication_patterns": (list, []),
            "input_artifacts": (dict, {}),
        },
    )

# ── Feature 007: Edge Case Analysis Engine ────────────────────────────

EDGE_CASE_MAX_PER_SERVICE: int = 30

EDGE_CASE_BASE_COUNT: int = 6
EDGE_CASE_PER_DEPENDENCY: int = 2
EDGE_CASE_PER_EVENT: int = 1
EDGE_CASE_PER_EXTRA_FEATURE: int = 2

STANDARD_EDGE_CASE_CATEGORIES: tuple[str, ...] = (
    "concurrency",
    "data_boundary",
    "state_machine",
    "ui_ux",
    "security",
    "data_migration",
)

MICROSERVICE_EDGE_CASE_CATEGORIES: tuple[str, ...] = (
    "service_unavailability",
    "network_partition",
    "eventual_consistency",
    "distributed_transaction",
    "version_skew",
    "data_ownership",
)

MODULAR_MONOLITH_EXTRA_CATEGORIES: tuple[str, ...] = (
    "interface_contract_violation",
)

SEVERITY_MATRIX_MICROSERVICE: dict[tuple[bool, str], str] = {
    (True, "sync-rest"): "critical",
    (True, "sync-grpc"): "critical",
    (True, "async-event"): "high",
    (False, "sync-rest"): "high",
    (False, "sync-grpc"): "high",
    (False, "async-event"): "medium",
}

SEVERITY_MATRIX_MONOLITH: dict[str, str] = {
    "security": "high",
    "concurrency": "high",
    "data_boundary": "medium",
    "state_machine": "medium",
    "ui_ux": "low",
    "data_migration": "low",
}

SEVERITY_DEFAULT_REQUIRED: str = "high"
SEVERITY_DEFAULT_OPTIONAL: str = "medium"
SEVERITY_DATA_OWNERSHIP: str = "high"
SEVERITY_INTERFACE_CONTRACT: str = "high"

EDGE_CASE_CATEGORY_PRIORITY: dict[str, int] = {
    "service_unavailability": 1,
    "distributed_transaction": 2,
    "network_partition": 3,
    "eventual_consistency": 4,
    "data_ownership": 5,
    "version_skew": 6,
    "interface_contract_violation": 7,
    "security": 8,
    "concurrency": 9,
    "data_boundary": 10,
    "state_machine": 11,
    "ui_ux": 12,
    "data_migration": 13,
}

# ── Task Generation Constants (Feature 008) ──────────────────────────

TASK_ID_PREFIX: str = "T"
CROSS_SERVICE_TASK_PREFIX: str = "X-T"
CROSS_SERVICE_TARGET: str = "cross-service-infra"
MAX_TASKS_PER_SERVICE: int = 50

EFFORT_SIZES: tuple[str, ...] = ("S", "M", "L", "XL")
EFFORT_BUMP_THRESHOLD_FEATURES: int = 3
EFFORT_BUMP_THRESHOLD_DEPS: int = 2

CROSS_SERVICE_CATEGORIES: tuple[str, ...] = (
    "shared_contracts",
    "docker_compose",
    "message_broker",
    "api_gateway",
    "shared_auth",
)

MICROSERVICE_STEP_COUNT: int = 14
MONOLITH_STEP_COUNT: int = 7

CONDITIONAL_STEPS: dict[str, str] = {
    "communication_clients": "dependencies",
    "event_handlers": "events",
    "contract_tests": "dependencies",
    "boundary_interface": "modular-monolith",
    "database": "entities",
}

# Effort bump table: category → (base, 3-4 features, 5+ features)
EFFORT_BUMP_TABLE: dict[str, tuple[str, str, str]] = {
    "scaffolding": ("S", "S", "M"),
    "domain_models": ("M", "L", "L"),
    "database": ("L", "L", "XL"),
    "repository": ("M", "L", "L"),
    "service_layer": ("L", "L", "XL"),
    "communication_clients": ("M", "L", "L"),
    "controllers": ("M", "L", "L"),
    "event_handlers": ("M", "M", "L"),
    "health_checks": ("S", "S", "S"),
    "contract_tests": ("L", "L", "XL"),
    "unit_tests": ("L", "XL", "XL"),
    "integration_tests": ("XL", "XL", "XL"),
    "container_optimization": ("S", "S", "M"),
    "gateway_config": ("S", "S", "M"),
    "folder_structure": ("S", "S", "M"),
    "repo_service": ("L", "L", "XL"),
    "boundary_interface": ("M", "M", "L"),
    "tests": ("L", "XL", "XL"),
}

# Plan.md required sections for validation (FR-015)
PLAN_REQUIRED_SECTIONS: tuple[str, ...] = (
    "Summary",
    "Technical Context",
    "Design Decisions",
)

# Governance scope-to-layer mapping for GovernanceReader
GOVERNANCE_SCOPE_TO_LAYERS: dict[str, tuple[str, ...]] = {
    "architecture": ("scaffolding", "domain_models", "service_layer"),
    "backend": (
        "service_layer", "repository", "controllers",
        "communication_clients", "event_handlers",
    ),
    "frontend": (),
    "database": ("database",),
    "security": ("controllers", "shared_auth", "health_checks"),
    "testing": ("unit_tests", "integration_tests", "contract_tests"),
    "cicd": ("container_optimization", "gateway_config"),
}

# Cross-service categories by architecture
CROSS_SERVICE_SCOPE: dict[str, tuple[str, ...]] = {
    "microservice": (
        "shared_contracts", "docker_compose",
        "message_broker", "api_gateway", "shared_auth",
    ),
    "modular-monolith": ("shared_contracts", "shared_auth"),
    "monolithic": (),
}

# ── Sub-Agent Executor Constants (Feature 009) ────────────────────────

EXECUTION_STATE_FILENAME: str = ".execution-state.json"
EXECUTION_LOCK_FILENAME: str = ".execution-lock"
EXECUTION_LOCK_STALE_MINUTES: int = 60

MAX_FIX_ATTEMPTS: int = 3
CONTEXT_TOKEN_BUDGET: int = 100_000
CHARS_PER_TOKEN_ESTIMATE: int = 4

AGENT_RETRY_DELAYS: tuple[int, ...] = (1, 2, 4)
HEALTH_CHECK_TIMEOUT: int = 30
HEALTH_CHECK_ENDPOINT: str = "/health"

DOCKER_COMPOSE_TEST_PROFILE: str = "test"

IMPLEMENTATION_MODES: tuple[str, ...] = ("prompt-display", "agent-call")

# Context priority order (lowest priority first — truncated first when over budget)
CONTEXT_PRIORITY: tuple[str, ...] = (
    "edge_cases",
    "architecture_prompts",
    "dependency_contracts",
    "data_model",
    "plan",
    "governance_prompts",
    "spec",
    "constitution",
    "current_task",
)

# ── Quality Validation Constants (Feature 010) ───────────────────────

ERROR_CATEGORIES: tuple[str, ...] = (
    "syntax", "logic", "type", "lint",
    "coverage", "docker", "contract", "boundary", "security",
)

CONTAINER_RELEVANT_PATTERNS: frozenset[str] = frozenset({
    "Dockerfile",
    "Dockerfile.*",
    "docker-compose*.yml",
    "docker-compose*.yaml",
    ".dockerignore",
    "requirements.txt",
    "package.json",
    "*.csproj",
})

SECRET_PATTERNS: tuple[tuple[str, str], ...] = (
    ("aws_access_key", r"(?:^|[\"'\s=])AKIA[0-9A-Z]{16}(?:[\"'\s]|$)"),
    ("aws_secret_key", r"(?:aws_secret_access_key|secret_key)\s*[:=]\s*[\"']?[A-Za-z0-9/+=]{40}"),
    ("generic_api_key", r"(?:api[_-]?key|apikey)\s*[:=]\s*[\"']?[A-Za-z0-9_\-]{20,}"),
    ("jwt_token", r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"),
    ("private_key", r"-----BEGIN\s+(?:RSA|DSA|EC|OPENSSH)\s+PRIVATE\s+KEY-----"),
    ("connection_string", r"(?:mongodb|postgres|mysql|redis)://[^\s\"']+:[^\s\"']+@"),
    ("generic_secret", r"(?:secret|password|passwd|token)\s*[:=]\s*[\"'][^\s\"']{8,}[\"']"),
    ("github_token", r"gh[ps]_[A-Za-z0-9_]{36,}"),
)

THRESHOLD_KEY_MAPPING: dict[str, str] = {
    "max_function_lines": "line-limit:function",
    "max_class_lines": "line-limit:class",
    "min_coverage_percent": "coverage",
    "max_lines": "line-limit:generic",
}

MAX_FUNCTION_LINES: int = 30
MAX_CLASS_LINES: int = 200
ENTROPY_THRESHOLD: float = 4.5

TODO_PATTERNS: tuple[str, ...] = (
    r"\bTODO\b",
    r"\bFIXME\b",
    r"\bHACK\b",
    r"\bXXX\b",
)

TEST_FIXTURE_PATTERNS: frozenset[str] = frozenset({
    "tests/",
    "test_",
    "conftest.py",
    "fixtures/",
    "**/testdata/",
})

# ── Integration Orchestrator Constants (Feature 011) ──────────────────

ORCHESTRATION_STATE_FILENAME: str = ".specforge/orchestration-state.json"
ORCHESTRATION_LOCK_FILENAME: str = ".specforge/.orchestration-lock"
ORCHESTRATION_LOCK_STALE_MINUTES: int = 120
INTEGRATION_REPORT_FILENAME: str = "integration-report.md"
DOCKER_COMPOSE_UP_TIMEOUT: int = 120
HEALTH_CHECK_POLL_INTERVAL: int = 2
HEALTH_CHECK_MAX_RETRIES: int = 30

ORCHESTRATION_PHASE_STATUSES: tuple[str, ...] = (
    "pending", "in-progress", "completed", "partial", "failed",
)
ORCHESTRATION_STATUSES: tuple[str, ...] = (
    "pending", "in-progress", "completed", "failed", "halted",
)
SHARED_INFRA_STATUSES: tuple[str, ...] = (
    "pending", "in-progress", "completed", "failed", "skipped",
)
VERIFICATION_SEVERITIES: tuple[str, ...] = ("error", "warning")
REPORT_VERDICTS: tuple[str, ...] = ("pass", "fail", "partial")
ORCHESTRATION_SCHEMA_VERSION: str = "1.0"

# ── Feature 012: Project Status Dashboard ──────────────────────────────

STATUS_REPORT_DIR: str = ".specforge/reports"
STATUS_JSON_FILENAME: str = "status.json"
STATUS_MD_FILENAME: str = "status.md"
QUALITY_REPORT_FILENAME: str = ".quality-report.json"

ServiceOverallStatus = Literal[
    "COMPLETE",
    "IN_PROGRESS",
    "PLANNING",
    "NOT_STARTED",
    "BLOCKED",
    "FAILED",
    "UNKNOWN",
]

SERVICE_STATUS_ALL: tuple[str, ...] = (
    "COMPLETE",
    "IN_PROGRESS",
    "PLANNING",
    "NOT_STARTED",
    "BLOCKED",
    "FAILED",
    "UNKNOWN",
)

STATUS_DISPLAY_LABELS: dict[str, str] = {
    "COMPLETE": "COMPLETE",
    "IN_PROGRESS": "IN PROGRESS",
    "PLANNING": "PLANNING",
    "NOT_STARTED": "NOT STARTED",
    "BLOCKED": "BLOCKED",
    "FAILED": "FAILED",
    "UNKNOWN": "UNKNOWN",
}

LIFECYCLE_PHASE_DISPLAY: tuple[str, ...] = ("DONE", "WIP")

PIPELINE_TO_LIFECYCLE: dict[str, str] = {
    "spec": "spec",
    "plan": "plan",
    "tasks": "tasks",
}

STATUS_SCHEMA_VERSION: str = "1.0"

WATCH_DEFAULT_INTERVAL: int = 5
