"""Hard-coded domain pattern dictionaries for feature decomposition.

Each domain contains weighted keywords for matching and feature templates
for generation. This is a data module — no logic, pure declarations.
Six built-in domains + one generic fallback (FR-038, FR-049).
"""

from __future__ import annotations

# ── Finance Domain ───────────────────────────────────────────────────

_FINANCE: dict = {
    "name": "finance",
    "keywords": [
        ("finance", 3),
        ("banking", 3),
        ("payment", 3),
        ("transaction", 3),
        ("ledger", 2),
        ("budget", 2),
        ("invoice", 2),
        ("accounting", 2),
        ("money", 2),
        ("wallet", 2),
        ("expense", 2),
        ("investment", 2),
        ("loan", 1),
        ("tax", 1),
        ("portfolio", 1),
        ("savings", 1),
    ],
    "features": [
        {
            "name": "authentication",
            "description": "User registration, login, MFA, session management",
            "category": "foundation",
            "priority": "P0",
            "always_separate": True,
            "data_keywords": ["user", "session", "credential"],
        },
        {
            "name": "account-management",
            "description": "Bank account CRUD, account types, balances",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["account", "balance", "user"],
        },
        {
            "name": "transactions",
            "description": "Deposits, withdrawals, transfers between accounts",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["transaction", "account", "balance"],
        },
        {
            "name": "budgeting",
            "description": "Budget creation, tracking, category-based spending limits",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["budget", "category", "spending"],
        },
        {
            "name": "bill-payments",
            "description": "Scheduled and recurring bill payments",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["bill", "payment", "schedule"],
        },
        {
            "name": "reporting",
            "description": "Financial reports, spending analytics, export to PDF/CSV",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["report", "analytics", "export"],
        },
        {
            "name": "notifications",
            "description": "Transaction alerts, budget warnings, bill reminders",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["notification", "alert", "reminder"],
        },
        {
            "name": "external-integrations",
            "description": "Bank API connections, payment gateway, credit score",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["api", "gateway", "external"],
        },
        {
            "name": "investment-tracking",
            "description": "Portfolio tracking, stock/fund performance",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["investment", "portfolio", "asset"],
        },
        {
            "name": "goals-savings",
            "description": "Savings goals, progress tracking, auto-save rules",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["goal", "savings", "target"],
        },
        {
            "name": "admin-dashboard",
            "description": "Admin panel for user management, system config, audit logs",
            "category": "admin",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["admin", "audit", "config"],
        },
        {
            "name": "tax-tools",
            "description": "Tax categorization, deduction tracking, report generation",
            "category": "supporting",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["tax", "deduction", "category"],
        },
    ],
}

# ── E-commerce Domain ────────────────────────────────────────────────

_ECOMMERCE: dict = {
    "name": "ecommerce",
    "keywords": [
        ("ecommerce", 3),
        ("e-commerce", 3),
        ("shop", 3),
        ("store", 3),
        ("cart", 3),
        ("product", 2),
        ("checkout", 2),
        ("order", 2),
        ("catalog", 2),
        ("inventory", 2),
        ("marketplace", 2),
        ("shipping", 1),
        ("payment", 1),
        ("retail", 1),
    ],
    "features": [
        {
            "name": "authentication",
            "description": "User registration, login, OAuth, session management",
            "category": "foundation",
            "priority": "P0",
            "always_separate": True,
            "data_keywords": ["user", "session", "credential"],
        },
        {
            "name": "product-catalog",
            "description": "Product listing, categories, search, filters",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["product", "category", "catalog"],
        },
        {
            "name": "shopping-cart",
            "description": "Cart management, item quantities, price calculation",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["cart", "item", "price"],
        },
        {
            "name": "checkout-payments",
            "description": "Checkout flow, payment processing, order confirmation",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["order", "payment", "checkout"],
        },
        {
            "name": "order-management",
            "description": "Order tracking, status updates, history, returns",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["order", "status", "return"],
        },
        {
            "name": "inventory-management",
            "description": "Stock levels, reorder alerts, warehouse management",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["inventory", "stock", "warehouse"],
        },
        {
            "name": "shipping-delivery",
            "description": "Shipping rates, carrier integration, delivery tracking",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["shipping", "delivery", "carrier"],
        },
        {
            "name": "reviews-ratings",
            "description": "Product reviews, star ratings, review moderation",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["review", "rating", "product"],
        },
        {
            "name": "notifications",
            "description": "Order updates, shipping alerts, promotional emails",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["notification", "email", "alert"],
        },
        {
            "name": "search-discovery",
            "description": "Full-text search, recommendations, personalization",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["search", "recommendation", "product"],
        },
        {
            "name": "admin-dashboard",
            "description": "Store management, sales analytics, user management",
            "category": "admin",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["admin", "analytics", "management"],
        },
        {
            "name": "promotions-discounts",
            "description": "Coupon codes, flash sales, discount rules",
            "category": "supporting",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["coupon", "discount", "promotion"],
        },
    ],
}

# ── SaaS Domain ──────────────────────────────────────────────────────

_SAAS: dict = {
    "name": "saas",
    "keywords": [
        ("saas", 3),
        ("subscription", 3),
        ("tenant", 3),
        ("multi-tenant", 3),
        ("platform", 2),
        ("dashboard", 2),
        ("billing", 2),
        ("workspace", 2),
        ("team", 2),
        ("api", 1),
        ("webhook", 1),
        ("analytics", 1),
        ("plan", 1),
    ],
    "features": [
        {
            "name": "authentication",
            "description": "User registration, login, SSO, team invitations",
            "category": "foundation",
            "priority": "P0",
            "always_separate": True,
            "data_keywords": ["user", "session", "credential", "team"],
        },
        {
            "name": "tenant-management",
            "description": "Multi-tenant workspaces, org settings, member roles",
            "category": "foundation",
            "priority": "P0",
            "always_separate": False,
            "data_keywords": ["tenant", "workspace", "organization"],
        },
        {
            "name": "subscription-billing",
            "description": "Plan management, payment processing, invoicing",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["subscription", "plan", "invoice", "payment"],
        },
        {
            "name": "core-product",
            "description": "Primary product functionality and value delivery",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["product", "feature", "data"],
        },
        {
            "name": "user-management",
            "description": "Roles, permissions, team management, access control",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["user", "role", "permission"],
        },
        {
            "name": "dashboard-analytics",
            "description": "Usage analytics, metrics dashboard, reporting",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["analytics", "metric", "report"],
        },
        {
            "name": "notifications",
            "description": "In-app notifications, email alerts, webhook events",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["notification", "email", "webhook"],
        },
        {
            "name": "api-integrations",
            "description": "REST API, webhooks, third-party integrations",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["api", "webhook", "integration"],
        },
        {
            "name": "settings-configuration",
            "description": "App settings, preferences, feature flags",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["setting", "config", "preference"],
        },
        {
            "name": "audit-logging",
            "description": "Activity logs, change tracking, compliance audit trail",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["audit", "log", "activity"],
        },
        {
            "name": "admin-dashboard",
            "description": "System admin, tenant overview, support tools",
            "category": "admin",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["admin", "system", "support"],
        },
        {
            "name": "onboarding",
            "description": "User onboarding flow, setup wizard, tutorials",
            "category": "supporting",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["onboarding", "setup", "tutorial"],
        },
    ],
}

# ── Social Domain ────────────────────────────────────────────────────

_SOCIAL: dict = {
    "name": "social",
    "keywords": [
        ("social", 3),
        ("social-media", 3),
        ("feed", 3),
        ("post", 2),
        ("friend", 2),
        ("follow", 2),
        ("message", 2),
        ("chat", 2),
        ("community", 2),
        ("profile", 1),
        ("share", 1),
        ("like", 1),
        ("comment", 1),
        ("network", 1),
    ],
    "features": [
        {
            "name": "authentication",
            "description": "User registration, login, social OAuth, sessions",
            "category": "foundation",
            "priority": "P0",
            "always_separate": True,
            "data_keywords": ["user", "session", "credential"],
        },
        {
            "name": "user-profiles",
            "description": "Profile pages, bios, avatars, privacy settings",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["user", "profile", "avatar"],
        },
        {
            "name": "content-feed",
            "description": "News feed, timeline, content ranking algorithm",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["post", "feed", "content"],
        },
        {
            "name": "social-connections",
            "description": "Follow/friend system, suggestions, connection graph",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["friend", "follow", "connection"],
        },
        {
            "name": "messaging",
            "description": "Direct messages, group chats, message history",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["message", "chat", "conversation"],
        },
        {
            "name": "content-creation",
            "description": "Post creation, media upload, editing, rich text",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["post", "media", "upload"],
        },
        {
            "name": "interactions",
            "description": "Likes, comments, shares, reactions",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["like", "comment", "share", "post"],
        },
        {
            "name": "notifications",
            "description": "Push notifications, activity alerts, mention alerts",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["notification", "alert", "push"],
        },
        {
            "name": "search-discovery",
            "description": "User search, content search, trending topics",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["search", "trending", "discover"],
        },
        {
            "name": "media-management",
            "description": "Image/video storage, processing, CDN delivery",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["media", "image", "video", "storage"],
        },
        {
            "name": "moderation",
            "description": "Content moderation, reporting, spam detection",
            "category": "admin",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["moderation", "report", "spam"],
        },
        {
            "name": "admin-dashboard",
            "description": "Platform admin, user management, analytics",
            "category": "admin",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["admin", "analytics", "management"],
        },
    ],
}

# ── Healthcare Domain ────────────────────────────────────────────────

_HEALTHCARE: dict = {
    "name": "healthcare",
    "keywords": [
        ("healthcare", 3),
        ("health", 3),
        ("medical", 3),
        ("patient", 3),
        ("clinic", 2),
        ("hospital", 2),
        ("doctor", 2),
        ("appointment", 2),
        ("ehr", 2),
        ("prescription", 2),
        ("diagnosis", 1),
        ("telehealth", 1),
        ("pharmacy", 1),
        ("wellness", 1),
    ],
    "features": [
        {
            "name": "authentication",
            "description": "User registration, login, role-based access",
            "category": "foundation",
            "priority": "P0",
            "always_separate": True,
            "data_keywords": ["user", "session", "credential", "role"],
        },
        {
            "name": "patient-records",
            "description": "Electronic health records, medical history, documents",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["patient", "record", "history"],
        },
        {
            "name": "appointment-scheduling",
            "description": "Booking, calendar management, availability, reminders",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["appointment", "schedule", "calendar"],
        },
        {
            "name": "prescriptions",
            "description": "Prescription management, refills, drug interactions",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["prescription", "medication", "drug"],
        },
        {
            "name": "provider-management",
            "description": "Doctor profiles, specialties, schedules, departments",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["provider", "doctor", "department"],
        },
        {
            "name": "billing-insurance",
            "description": "Medical billing, insurance claims, payment processing",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["billing", "insurance", "claim", "payment"],
        },
        {
            "name": "notifications",
            "description": "Appointment reminders, prescription alerts, results",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["notification", "reminder", "alert"],
        },
        {
            "name": "telehealth",
            "description": "Video consultations, virtual waiting room, screen sharing",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["telehealth", "video", "consultation"],
        },
        {
            "name": "lab-results",
            "description": "Lab test ordering, result tracking, report viewing",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["lab", "test", "result"],
        },
        {
            "name": "messaging",
            "description": "Secure patient-provider messaging, care team communication",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["message", "communication", "chat"],
        },
        {
            "name": "reporting-compliance",
            "description": "HIPAA compliance reports, analytics, audit trails",
            "category": "admin",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["report", "compliance", "audit"],
        },
        {
            "name": "admin-dashboard",
            "description": "System administration, user management, facility settings",
            "category": "admin",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["admin", "management", "facility"],
        },
    ],
}

# ── Education Domain ─────────────────────────────────────────────────

_EDUCATION: dict = {
    "name": "education",
    "keywords": [
        ("education", 3),
        ("learning", 3),
        ("course", 3),
        ("student", 3),
        ("lms", 3),
        ("school", 2),
        ("teacher", 2),
        ("classroom", 2),
        ("lesson", 2),
        ("quiz", 2),
        ("grade", 1),
        ("assignment", 1),
        ("tutorial", 1),
        ("training", 1),
    ],
    "features": [
        {
            "name": "authentication",
            "description": "User registration, login, role-based access",
            "category": "foundation",
            "priority": "P0",
            "always_separate": True,
            "data_keywords": ["user", "session", "credential", "role"],
        },
        {
            "name": "course-management",
            "description": "Course CRUD, curriculum design, module organization",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["course", "curriculum", "module"],
        },
        {
            "name": "content-delivery",
            "description": "Lesson content, video lectures, reading materials",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["content", "lesson", "video", "material"],
        },
        {
            "name": "assessments",
            "description": "Quizzes, exams, assignments, auto-grading",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["quiz", "exam", "assignment", "grade"],
        },
        {
            "name": "student-progress",
            "description": "Progress tracking, completion status, learning analytics",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["progress", "completion", "analytics"],
        },
        {
            "name": "enrollment",
            "description": "Course enrollment, waitlists, prerequisites",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["enrollment", "registration", "prerequisite"],
        },
        {
            "name": "discussions",
            "description": "Discussion forums, Q&A boards, peer interaction",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["discussion", "forum", "comment"],
        },
        {
            "name": "notifications",
            "description": "Assignment reminders, grade alerts, course announcements",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["notification", "reminder", "announcement"],
        },
        {
            "name": "grading-feedback",
            "description": "Grade management, rubrics, instructor feedback",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["grade", "rubric", "feedback"],
        },
        {
            "name": "certificates",
            "description": "Certificate generation, credential verification",
            "category": "supporting",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["certificate", "credential", "badge"],
        },
        {
            "name": "admin-dashboard",
            "description": "Platform admin, institution settings, user management",
            "category": "admin",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["admin", "institution", "management"],
        },
        {
            "name": "external-integrations",
            "description": "LTI tools, video conferencing, library systems",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["lti", "integration", "external"],
        },
    ],
}

# ── Generic Fallback ─────────────────────────────────────────────────

GENERIC_PATTERN: dict = {
    "name": "generic",
    "keywords": [],
    "features": [
        {
            "name": "authentication",
            "description": "User registration, login, session management",
            "category": "foundation",
            "priority": "P0",
            "always_separate": True,
            "data_keywords": ["user", "session", "credential"],
        },
        {
            "name": "core-crud",
            "description": "Primary data management — create, read, update, delete",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["data", "entity", "record"],
        },
        {
            "name": "user-management",
            "description": "User profiles, roles, permissions",
            "category": "core",
            "priority": "P1",
            "always_separate": False,
            "data_keywords": ["user", "role", "permission"],
        },
        {
            "name": "admin-panel",
            "description": "Admin dashboard, system configuration, user oversight",
            "category": "admin",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["admin", "config", "management"],
        },
        {
            "name": "reporting",
            "description": "Reports, analytics, data export",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["report", "analytics", "export"],
        },
        {
            "name": "notifications",
            "description": "Email and in-app notifications, alerts",
            "category": "integration",
            "priority": "P2",
            "always_separate": True,
            "data_keywords": ["notification", "email", "alert"],
        },
        {
            "name": "search",
            "description": "Full-text search, filters, sorting",
            "category": "supporting",
            "priority": "P2",
            "always_separate": False,
            "data_keywords": ["search", "filter", "index"],
        },
        {
            "name": "settings",
            "description": "Application settings and user preferences",
            "category": "supporting",
            "priority": "P3",
            "always_separate": False,
            "data_keywords": ["setting", "preference", "config"],
        },
    ],
}

# ── Public API ───────────────────────────────────────────────────────

DOMAIN_PATTERNS: list[dict] = [
    _FINANCE,
    _ECOMMERCE,
    _SAAS,
    _SOCIAL,
    _HEALTHCARE,
    _EDUCATION,
]
