"""Shared fixtures and factories for unit tests."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from specforge.core.config import GOVERNANCE_DOMAINS, PRECEDENCE_ORDER


def make_governance_fixtures(
    tmp_path: Path,
    stack: str,
    domains: list[str] | None = None,
) -> Path:
    """Write minimal but structurally valid governance files + config.json to tmp_path.

    Returns the project root (tmp_path).
    Each governance file follows the canonical ## Meta / ## Precedence / ## Rules format
    and is immediately parseable by PromptLoader._parse_prompt_file().
    """
    if domains is None:
        domains = list(GOVERNANCE_DOMAINS)

    prompts_dir = tmp_path / ".specforge" / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)

    # Domain precedence values matching PRECEDENCE_ORDER
    _PRECEDENCE_MAP: dict[str, int] = {
        "security": 1,
        "architecture": 2,
        "backend": 3,
        "frontend": 3,
        "database": 3,
        "testing": 4,
        "cicd": 5,
    }

    # Agnostic domains always use flat filename
    _AGNOSTIC_DOMAINS = frozenset({"architecture", "security"})

    for domain in domains:
        if domain in _AGNOSTIC_DOMAINS:
            filename = f"{domain}.prompts.md"
        elif stack == "agnostic":
            filename = f"{domain}.prompts.md"
        else:
            filename = f"{domain}.{stack}.prompts.md"

        precedence = _PRECEDENCE_MAP.get(domain, 3)
        # Use domain-namespaced rule ID prefix
        prefix = domain[:4].upper().rstrip("-")
        rule_id = f"{prefix}-001"

        content = f"""\
<!-- Generated by SpecForge - do not edit manually above the Rules section -->

# {domain.title()} Governance Prompt

## Meta
domain: {domain}
stack: {stack}
version: 1.0
precedence: {precedence}
checksum: abc123def456

## Precedence
This file occupies position {precedence} in the conflict-resolution hierarchy:
`security (1) > architecture (2) > backend/frontend/database (3) > testing (4) > cicd (5)`

When this file conflicts with a higher-precedence file, the higher-precedence
value applies. When this file conflicts with an equal-priority file, the conflict
is flagged as AMBIGUOUS and requires manual resolution.

## Rules

### {rule_id}: Test Rule
severity: ERROR
scope: all files
rule: All code MUST follow the governance rules for {domain}.
threshold: max_lines=100, min_coverage=80
example_correct: |
  # correct example for {domain}
example_incorrect: |
  # incorrect example for {domain}
"""
        (prompts_dir / filename).write_text(content, encoding="utf-8")

    # Write config.json
    config_dir = tmp_path / ".specforge"
    config_dir.mkdir(parents=True, exist_ok=True)
    config = {
        "project_name": "test-project",
        "stack": stack,
        "version": "1.0",
        "created_at": "2026-03-15",
    }
    (config_dir / "config.json").write_text(
        json.dumps(config, indent=2), encoding="utf-8"
    )

    return tmp_path


@pytest.fixture
def governance_fixtures_dotnet(tmp_path: Path) -> Path:
    """Convenience fixture: full dotnet governance project."""
    return make_governance_fixtures(tmp_path, stack="dotnet")


@pytest.fixture
def governance_fixtures_agnostic(tmp_path: Path) -> Path:
    """Convenience fixture: full agnostic governance project."""
    return make_governance_fixtures(tmp_path, stack="agnostic")
