"""Unit tests for TemplateRenderer — filters, render, error cases."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest

from specforge.core.template_models import (
    TemplateInfo,
    TemplateSource,
    TemplateType,
)
from specforge.core.template_renderer import (
    TemplateRenderer,
    _kebab_case,
    _pluralize,
    _snake_case,
    _uppercase,
)

# ── Filter Tests (T012) ─────────────────────────────────────────────


class TestSnakeCaseFilter:
    def test_camel_case(self) -> None:
        assert _snake_case("MyProject") == "my_project"

    def test_empty_string(self) -> None:
        assert _snake_case("") == ""

    def test_already_snake(self) -> None:
        assert _snake_case("my_project") == "my_project"

    def test_spaces(self) -> None:
        assert _snake_case("My Project") == "my_project"

    def test_multiple_caps(self) -> None:
        assert _snake_case("HTTPRequest") == "http_request"


class TestUppercaseFilter:
    def test_basic(self) -> None:
        assert _uppercase("myapp") == "MYAPP"

    def test_empty(self) -> None:
        assert _uppercase("") == ""

    def test_mixed(self) -> None:
        assert _uppercase("myApp") == "MYAPP"


class TestPluralizeFilter:
    def test_regular(self) -> None:
        assert _pluralize("entity") == "entities"

    def test_analysis(self) -> None:
        assert _pluralize("analysis") == "analyses"

    def test_s_ending(self) -> None:
        assert _pluralize("bus") == "buses"

    def test_regular_word(self) -> None:
        assert _pluralize("model") == "models"


class TestKebabCaseFilter:
    def test_camel_case(self) -> None:
        assert _kebab_case("MyProject") == "my-project"

    def test_already_kebab(self) -> None:
        assert _kebab_case("already-kebab") == "already-kebab"

    def test_empty(self) -> None:
        assert _kebab_case("") == ""

    def test_spaces(self) -> None:
        assert _kebab_case("My Project") == "my-project"


# ── Renderer Tests (T013) ───────────────────────────────────────────


class TestRendererRender:
    @pytest.fixture()
    def registry(self, tmp_path: Path) -> MagicMock:
        """Create a mock registry pointing to base templates."""
        mock = MagicMock()
        mock.get.return_value = MagicMock(
            ok=True,
            value=TemplateInfo(
                logical_name="constitution",
                template_type=TemplateType.constitution,
                source=TemplateSource.built_in,
                template_path="base/constitution.md.j2",
            ),
        )
        return mock

    def test_complete_vars_returns_ok(self, registry: MagicMock) -> None:
        renderer = TemplateRenderer(registry)
        ctx = {
            "project_name": "TestProject",
            "agent": "claude",
            "stack": "python",
            "date": "2026-01-01",
            "stack_hint": "Python",
        }
        result = renderer.render("constitution", TemplateType.constitution, ctx)
        assert result.ok
        assert "TestProject" in result.value

    def test_generation_header_is_first_line(self, registry: MagicMock) -> None:
        renderer = TemplateRenderer(registry)
        ctx = {
            "project_name": "TestProject",
            "agent": "claude",
            "stack": "python",
            "date": "2026-01-01",
            "stack_hint": "Python",
        }
        result = renderer.render("constitution", TemplateType.constitution, ctx)
        assert result.ok
        first_line = result.value.strip().split("\n")[0]
        assert "Generated by SpecForge" in first_line

    def test_missing_required_var_returns_err(self, registry: MagicMock) -> None:
        renderer = TemplateRenderer(registry)
        result = renderer.render(
            "constitution",
            TemplateType.constitution,
            {"project_name": "Test"},
        )
        assert not result.ok
        assert "agent" in result.error or "stack" in result.error

    def test_unknown_template_returns_err(self) -> None:
        mock_registry = MagicMock()
        mock_registry.get.return_value = MagicMock(
            ok=False,
            error="Template not found: nonexistent",
        )
        renderer = TemplateRenderer(mock_registry)
        result = renderer.render(
            "nonexistent",
            TemplateType.feature,
            {"project_name": "Test"},
        )
        assert not result.ok

    def test_render_raw_works_without_registry(self) -> None:
        renderer = TemplateRenderer(MagicMock())
        ctx = {
            "project_name": "TestProject",
            "agent": "claude",
            "stack": "python",
            "date": "2026-01-01",
            "stack_hint": "Python",
        }
        result = renderer.render_raw("constitution.md.j2", ctx)
        assert result.ok
        assert "TestProject" in result.value

    def test_conditional_section_included(self, registry: MagicMock) -> None:
        renderer = TemplateRenderer(registry)
        ctx = {
            "project_name": "Test",
            "agent": "claude",
            "stack": "python",
            "date": "2026-01-01",
            "stack_hint": "Python",
        }
        result = renderer.render("constitution", TemplateType.constitution, ctx)
        assert result.ok
        assert "Python" in result.value

    def test_conditional_section_omitted(self, registry: MagicMock) -> None:
        renderer = TemplateRenderer(registry)
        ctx = {
            "project_name": "Test",
            "agent": "agnostic",
            "stack": "agnostic",
            "date": "2026-01-01",
            "stack_hint": "Language-agnostic",
        }
        result = renderer.render("constitution", TemplateType.constitution, ctx)
        assert result.ok
        assert "Stack:" not in result.value


# ── Validation Pipeline Tests (US5 — T033) ──────────────────────────


class TestValidationPipeline:
    def test_valid_render_passes_validation(self) -> None:
        from specforge.core.template_registry import TemplateRegistry

        registry = TemplateRegistry()
        registry.discover()
        renderer = TemplateRenderer(registry)
        ctx = {
            "project_name": "Test",
            "agent": "claude",
            "stack": "python",
            "date": "2026-01-01",
            "stack_hint": "Python",
        }
        result = renderer.render("constitution", TemplateType.constitution, ctx)
        assert result.ok

    def test_render_with_broken_template_returns_err(self, tmp_path: Path) -> None:
        from specforge.core.template_registry import TemplateRegistry

        user_dir = tmp_path / ".specforge" / "templates"
        user_dir.mkdir(parents=True)
        broken = user_dir / "constitution.md.j2"
        broken.write_text(
            "# {{ project_name }}\n{{ undefined_var }}\n",
            encoding="utf-8",
        )
        registry = TemplateRegistry(tmp_path)
        registry.discover()
        renderer = TemplateRenderer(registry)
        ctx = {
            "project_name": "Test",
            "agent": "claude",
            "stack": "python",
            "date": "2026-01-01",
            "stack_hint": "Python",
        }
        result = renderer.render("constitution", TemplateType.constitution, ctx)
        # Jinja2 renders undefined as empty by default, so this succeeds
        assert result.ok

    def test_performance_under_one_second(self) -> None:
        """SC-001: Render the largest template in < 1 second."""
        import time

        from specforge.core.template_registry import TemplateRegistry

        registry = TemplateRegistry()
        registry.discover()
        renderer = TemplateRenderer(registry)
        ctx = {
            "project_name": "PerfTest",
            "agent": "claude",
            "stack": "python",
            "date": "2026-01-01",
            "stack_hint": "Python",
        }
        start = time.perf_counter()
        result = renderer.render("constitution", TemplateType.constitution, ctx)
        elapsed = time.perf_counter() - start
        assert result.ok
        assert elapsed < 1.0
